config/routes.rb
Rails.application.routes.draw do

  resources :produtos, only: [:new, :create, :destroy, :edit, :update]
  #resources :produtos
  root "produtos#index"
  get "/produtos/busca" => "produtos#busca", as: :busca_produto

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/produto.rb
class Produto < ApplicationRecord

  validates :quantidade, presence: true
  validates :preco, presence: true

  validates :nome, length: {minimum: 5}
  validates :descricao, length: {minimum: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

  def index
    @produtos = Produto.order :nome
  end

  def new
    @produto = Produto.new
  end

  def create

    valores = params.require(:produto).permit :nome, :descricao, :quantidade, :preco
    @produto = Produto.new valores
    if @produto.save
      flash[:notice] = "Produto salvo com sucesso"
      redirect_to root_url
    else
      render :new
    end

  end
  def edit
    id = params[:id]
    @produto = Produto.find(id)
    render :alterar
  end
  def update
    id = params[:id]
    @produto = Produto.find(id)
    valores = params.require(:produto).permit :nome, :preco, :descricao, :quantidade
    if @produto.update valores
      flash[:notice] = "Produto atualizado com sucesso"
      redirect_to root_url
    else
      render :alterar
    end
  end
  def destroy
    id = params[:id]
    Produto.destroy id
    redirect_to root_url
  end
  def busca
    nome = params[:nome]
    @produtos = Produto.where "nome like ?", nome
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Controledeestoque</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= nav_bar brand: "Controle de Estoque", brand_link: root_url do%>
      <%= form_tag busca_produto_path, method: :get, class: "navbar-form navbar-right" do %>
        <div class="form-group">
          <%= text_field_tag :nome, nil, class:"form-control"%>
          <%= button_to "Buscar", nil, class: "btn btn-default" %>
        </div>
      <%end%>

    <%end%>
    <div class="container"
      <%= yield %>
    </div>
  </body>
</html>

app/views/produtos/alterar.html.erb
<html>
<body>
<% @produto.errors.full_messages.each do |message| %>
  <div class="alert alert-danger" role="alert"><%=message%></div>
<% end %>



  <%= form_for @produto do |f| %>
  <div class="form-group">
    <%= f.label :nome %>
    <%= f.text_field :nome, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :descricao %>
    <%= f.text_area :descricao, class: "form-control", rows: 4 %>
  </div>
  <div class="form-inline">
    <div class="form-group">
      <%= f.label :quantidade %>
      <%= f.number_field :quantidade, step: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :preco %>
      <%= f.number_field :preco, step: 0.01, class: "form-control" %>
    </div>
      <%= f.submit "Atualizar o produto", class: "btn btn-primary" %>
  </div>
  <% end %>


</body>
</html>

app/views/produtos/busca.html.erb
<html>
<body>




<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Quantidade</th>
            <th>Preço</th>
            <th>Id</th>
        </tr>
    </thead>
    <tbody>
        <% @produtos.each do |produto| %>
        <tr>
            <td><%= produto.nome %></td>
            <td><%= produto.descricao %></td>
            <td><%= produto.quantidade %></td>
            <td><%= produto.preco %></td>
            <td><%= produto.id %></td>
            <td><%= button_to "Remover", produto, method: :delete, class: "btn btn-danger", data: {confirm: "Tem certeza que deseja remover?"} %>
            <td><%= link_to "Alterar", edit_produto_path(produto), class:"btn btn-default" %>
        </tr>
        <% end %>
    </tbody>
</table>
<%= link_to "Criar novo produto", new_produto_path, class:"btn btn-primary"%>

</body>
</html>

app/views/produtos/create.html.erb
<html>
Criado!
</html>

app/views/produtos/index.html.erb
<html>
<body>
  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert"><%= flash[:notice]%></div>
  <% end %>




<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Quantidade</th>
            <th>Preço</th>
            <th>Id</th>
        </tr>
    </thead>
    <tbody>
        <% @produtos.each do |produto| %>
        <tr>
            <td><%= produto.nome %></td>
            <td><%= produto.descricao %></td>
            <td><%= produto.quantidade %></td>
            <td><%= produto.preco %></td>
            <td><%= produto.id %></td>
            <td><%= button_to "Remover", produto, method: :delete, class: "btn btn-danger", data: {confirm: "Tem certeza que deseja remover?"} %>
            <td><%= link_to "Alterar", edit_produto_path(produto), class:"btn btn-default" %>
        </tr>
        <% end %>
    </tbody>
</table>
<%= button_to "Criar novo produto", new_produto_path, method: :get, class:"btn btn-primary" %>

</body>
</html>

app/views/produtos/new.html.erb
<html>
<body>
<% @produto.errors.full_messages.each do |message| %>
  <div class="alert alert-danger" role="alert"><%=message%></div>
<% end %>



  <%= form_for @produto do |f| %>
  <div class="form-group">
    <%= f.label :nome %>
    <%= f.text_field :nome, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :descricao %>
    <%= f.text_area :descricao, class: "form-control", rows: 4 %>
  </div>
  <div class="form-inline">
    <div class="form-group">
      <%= f.label :quantidade %>
      <%= f.number_field :quantidade, step: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :preco %>
      <%= f.number_field :preco, step: 0.01, class: "form-control" %>
    </div>
      <%= f.submit "Criar o produto", class: "btn btn-primary" %>
  </div>
  <% end %>


</body>
</html>